import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import Card from '../components/card'
import coffeeStoresData from '../data/coffee-stores.json'

export async function getStaticProps(context) {
  const options = {
    method: 'GET',
    headers: {
      Accept: 'application/json',
      Authorization: 'fsq3leKQt6GWLWEnIdlWvsWVrjqyyCm45flt+wS6yWMmCZo='
    }
  };
  
  fetch('https://api.foursquare.com/v3/places/nearby?ll=24.994480%2C%20121.496410&hacc=1.22&altitude=1.22&query=coffee&limit=8', options)
    .then(response => response.json())
    .then(response => console.log(response))
    .catch(err => console.error(err));
  
  return {
    props: { coffeeStoresData, },
  } // prefetch coffeeStores from imported json data
}

export default function Home(props) {
  console.log('props', props)

  const handleBannerBtnClick = () => {
    console.log("Desiring Handle Banner Button Click");
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby" handleOnClick={handleBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/Cafe-Coffee-PNG-Free-Download.png" width={400} height={400}></Image>
        </div>
        {coffeeStoresData.length > 0 &&
          <>
            <h2 className={styles.heading2}>Toronto coffee stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStoresData.map((coffeeStore) => {
                return (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl}
                    href={`/coffee-store/${coffeeStore.id}`}
                    className={styles.card}
                  />);
              })}
            </div>
          </>}
      </main>
    </div>
  )
}
