import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Banner from '../components/banner'
import Card from '../components/card'

import Image from 'next/image'

export default function Home() {

  const handleBannerBtnClick = () => {
    console.log("Desiring Handle Banner Button Click");
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby" handleOnClick={handleBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/Cafe-Coffee-PNG-Free-Download.png" width={400} height={400}></Image>
        </div>
        <div className={styles.cardLayout}>
          <Card 
            name="DarkHorse Coffee" 
            imgUrl="/static/omlet.jpeg" 
            href="/coffee-store/darkhorse-coffee"
            className={styles.card}
          />
          <Card 
            name="DarkHorse Coffee" 
            imgUrl="/static/omlet.jpeg" 
            href="/coffee-store/darkhorse-coffee"
            className={styles.card}
          />
          <Card 
            name="DarkHorse Coffee" 
            imgUrl="/static/omlet.jpeg" 
            href="/coffee-store/darkhorse-coffee"
            className={styles.card}
          />
        </div>
      </main>
    </div>
  );
};
